#!/usr/bin/env bash
set -eu
trap "exit" 2

HELP=$(cat <<EOF
Usage: ./restart [options]

restart must be run from the root of the environment.

Options:
    -e, --elk                        Set up ELK stack
    -r, --reset                      Reset the environment
    -s, --sentry                     Set up Sentry
EOF
)

SERVICES=('')

reset_environment=false
while [[ $# -gt 0 ]]
do
  arg="$1"
  case $arg in
    -r|--reset)
    reset_environment=true
    shift
    ;;
    -e|--elk)
    SERVICES+=('-e')
    shift
    ;;
    -s|--sentry)
    SERVICES+=('-s')
    shift
    ;;
    -h |--help | *)
      printf "$HELP\n"
      exit 1
    ;;
  esac
done

ENGINE_DOMAIN=${ENGINE_DOMAIN:="localhost:8080"}
ENGINE_EMAIL=${ENGINE_EMAIL:="support@place.tech"}
ENGINE_PASSWORD=${ENGINE_PASSWORD:="development"}
RETHINKDB_HOST=${RETHINKDB_HOST:-"rethink"}
ELASTIC_HOST=${ES_HOST:-"elastic"}

RED='\033[0;31m'
NC='\033[0m'
script_name="$(basename "${0}")"
env_repo="partner-environment"
current_repo="$(basename "$(git --git-dir="./.git" remote get-url origin 2> /dev/null)")"
if [[ "${current_repo}" != "${env_repo}"* ]]
then
    printf "${RED}error:${NC} ${script_name} expected to be ran from root of the environment\n"
    exit 1
fi

echo "=== Pulling Backoffice..."
git clone -b beta "https://github.com/placeos/www-core" "www" 2> /dev/null || git -C "www" pull

echo "=== Pulling Drivers..."
git clone "https://github.com/placeos/drivers" "drivers" 2> /dev/null || git -C "drivers" pull

echo "=== Refreshing services..."
./scripts/start-services ${SERVICES[@]} || (printf "\nfailed to start services\n" && exit 1)

if [[ $reset_environment == "true" ]]
then
    printf "\n=== Dropping tables..."
    until $(docker exec -w /play play crystal run sam.cr -- drop:db -host="$RETHINKDB_HOST" @ drop:elastic -host="$ELASTIC_HOST" &> /dev/null)
    do
        printf '.'
        sleep 0.5
    done
    echo " done"

    printf "=== Initiating engine with default domain ($ENGINE_DOMAIN)..."
    ./scripts/generate-minimal-entities.sh "$ENGINE_DOMAIN/backoffice" "$ENGINE_EMAIL" "$ENGINE_PASSWORD" \
        && echo " done" || (printf "\nFailed to create user entity\n" && exit 1)

    printf "=== Creating placeholder documents..."
     docker exec -it -e "RETHINKDB_HOST=$RETHINKDB_HOST" -w /play play crystal run sam.cr -- generate:documents 2> /dev/null \
        && echo " done" || echo " failed"

    docker-compose restart nginx
fi

echo -e "\n\n=== Restart complete. Login to http://$ENGINE_DOMAIN/backoffice/ with"
echo "$ENGINE_EMAIL:$ENGINE_PASSWORD"
