#! /usr/bin/env bash

source .env || "couldn't locate .env"

image="placeos/init:${PLACE_INIT_TAG:-latest}"

docker pull "${image}"

docker run --rm -v "${PWD}:/tmp/secrets" -w /tmp/secrets -- "${image}" generate-secrets
