#! /usr/bin/env bash
set -e

secret_key_env=".env.secret_key"
public_key_env=".env.public_key"
env=".env"

set -a
if [[ -f "${secret_key_env}" ]]; then
    . ${secret_key_env}
fi
if [[ -f "${public_key_env}" ]]; then
    . ${public_key_env}
fi
. ${env}
set +a

if [[ -z "${JWT_PUBLIC}" || -z "${JWT_SECRET}" ]]; then
  dir=$(mktemp -d)

  ssh-keygen -t rsa -b 4096 -m PEM -f "${dir}/secret" -N "" &> /dev/null
  openssl rsa -in "${dir}/secret" -pubout -outform PEM -out "${dir}/public" 0>&- &> /dev/null

  secret="JWT_SECRET=$(base64 -i "${dir}/secret")"
  echo "${secret}" > .env.secret_key

  public="JWT_PUBLIC=$(base64 -i "${dir}/public")"
  echo "${public}" > .env.public_key

  echo "generated JWT_SECRET and JWT_PUBLIC"

  rm -r "${dir}"
else
  echo "already generated JWT_SECRET and JWT_PUBLIC"
fi
