#!/usr/bin/env bash

set -eu

cd "$(dirname "$0")"
mkdir -p ../ssl/default-domain
cd ../ssl/default-domain

openssl req -newkey rsa:2048 -nodes -days 365 -x509 \
  -subj "/C=AU/ST=NSW/L=Sydney/O=PlaceOS/CN=$1" \
  -keyout privkey.pem -out fullchain.pem

openssl dhparam -out ../dhparam.pem 1024
