#! /usr/bin/env bash

if [[ $(uname) == "Linux" ]]
then
  echo "Host is Linux, enabling /proc and /sys/fs/cgroup Metricbeat monitoring"
  if [[ $(grep METRICBEAT_PROC_PATH .env -c) == "0" ]]
  then
    echo METRICBEAT_PROC_PATH=/proc >> .env
  fi
  if [[ $(grep METRICBEAT_CGROUP_PATH .env -c) == "0" ]]
  then
    echo METRICBEAT_CGROUP_PATH=/sys/fs/cgroup >> .env
  fi
else
  echo "Host is not Linux, disabling /proc and /sys/fs/cgroup Metricbeat monitoring"
  sed -i '/METRICBEAT_.*_PATH/d' .env
fi
