#! /usr/bin/env bash

if [[ $(uname) == "Linux" ]]; then
    echo "Host is Linux, enabling metricbeat"
    if [[ $(grep "metricbeat:" docker-compose.yml -c) == "0" ]]; then
        cat compose-files/metricbeat.yml >>docker-compose.yml
    fi
fi
