#!/usr/bin/env bash
set -euo pipefail

# Path of installation directory
base_path="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)/../"

COMPOSE_PROJECT_NAME=placeos \
    docker-compose \
        --project-directory="$base_path" \
        run --rm init start
